# Generated by Django 3.1 on 2020-08-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='pro_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
