# Generated by Django 3.1 on 2020-08-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20200828_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='contact',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
