# Generated by Django 3.1 on 2020-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_auto_20200828_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
