# Generated by Django 3.1 on 2020-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_follow_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
